import { router, useForm, usePoll } from '@inertiajs/react';
import { useState } from 'react';
import { Shell, Panel, Field, Badge, Errors, Empty, Pages, root, inputClass, primary, secondary, statuses, stages, date, safeUrl } from './shared';

const empty = { name: '', url: '', allowed_hosts: '', keywords: '钢模板,钢结构,桥梁,采购,中标,成交', enabled: false, adapter: 'html', interval_minutes: 720 };
export default function Admin({ sources = [], runs = { data: [] } }) {
    const review = useForm({ runId: '', action: 'research', note: '' });
    const [editing, setEditing] = useState(null);
    const form = useForm(empty);
    usePoll(15000, { only: ['sources', 'runs'] });
    function save(e) { e.preventDefault(); const options = { preserveScroll: true, onSuccess: () => { setEditing(null); form.setData(empty); } }; if (editing) form.put(`${root}/sources/${editing}`, options); else form.post(`${root}/sources`, options); }
    return <Shell title="来源与 Agent 管理"><a href="/procurement-hub/company" className="text-sm text-steel">查看旧版独立企业资料档案（无需维护，不参与推荐） →</a><div className="grid gap-3 md:grid-cols-4">{[['信息采集', '公开公告与历史证据'], ['数据分析', '集团、供应商与可比价格'], ['综合推荐', '企业能力与我方业绩'], ['统筹审计', '任务安排与证据复核']].map(([name, description]) => <div className="rounded-xl border border-slate-200 bg-white p-4" key={name}><h2 className="font-semibold text-steel">{name} Agent</h2><p className="mt-2 text-xs leading-6 text-slate-500">{description}</p></div>)}</div>
    <Panel title={editing ? '编辑来源' : '登记公开来源'}><form className="grid gap-3 md:grid-cols-3" onSubmit={save}><Field label="来源名称"><input className={inputClass} required value={form.data.name} onChange={(e) => form.setData('name', e.target.value)} /></Field><div className="md:col-span-2"><Field label="当前公告列表入口"><input className={inputClass} type="url" required value={form.data.url} onChange={(e) => form.setData('url', e.target.value)} /></Field></div><Field label="允许公开域名（逗号分隔）"><input className={inputClass} required value={form.data.allowed_hosts} onChange={(e) => form.setData('allowed_hosts', e.target.value)} placeholder="example.com,www.example.com" /></Field><Field label="匹配关键词"><input className={inputClass} value={form.data.keywords} onChange={(e) => form.setData('keywords', e.target.value)} /></Field><Field label="更新间隔（分钟）"><input className={inputClass} type="number" min="60" max="10080" value={form.data.interval_minutes} onChange={(e) => form.setData('interval_minutes', Number(e.target.value))} /></Field><Field label="接入状态"><select className={inputClass} value={form.data.adapter} onChange={(e) => form.setData('adapter', e.target.value)}><option value="html">公开页面采集</option>{Object.entries({powerchina:"中国电建公开接口",shudao:"蜀道公开接口",worldbank:"世界银行公开接口",ted:"欧盟 TED 公开接口",fts:"英国 FTS 公开接口",ungm:"UNGM 公开搜索"}).map(([value,label]) => <option key={value} value={value}>{label}</option>)}<option value="unverified">待验证 / 待接口接入</option></select></Field><label className="hub-check flex items-center gap-2 text-sm"><input type="checkbox" checked={form.data.enabled} onChange={(e) => form.setData('enabled', e.target.checked)} />确认来源并启用持续采集</label><button className={primary} disabled={form.processing}>保存来源</button><div className="md:col-span-3"><Errors errors={form.errors} /></div></form></Panel>
    <Panel title="来源覆盖与状态">{sources.length ? <div className="flex flex-col gap-3">{sources.map((s) => <article key={s.id} className="rounded-lg border border-slate-200 p-4"><div className="flex flex-wrap items-center gap-3"><h3 className="grow font-medium">{s.name}</h3><Badge>{s.enabled ? statuses[s.status] || s.status : '未启用'}</Badge><button className={secondary} onClick={() => { setEditing(s.id); form.setData({ name: s.name, url: s.url, allowed_hosts: s.allowed_hosts.join(','), keywords: (s.keywords || []).join(','), enabled: s.enabled, adapter: s.adapter, interval_minutes: s.interval_minutes }); window.scrollTo({ top: 0, behavior: 'smooth' }); }}>编辑来源</button><button className={secondary} disabled={!s.enabled || s.adapter === 'unverified'} onClick={() => router.post(`${root}/sources/${s.id}/collect`, {}, { preserveScroll: true })}>立即采集</button></div>{safeUrl(s.url) && <a className="mt-2 block break-all text-sm text-steel underline" href={s.url} target="_blank" rel="noopener noreferrer">{s.url}</a>}<p className="mt-2 text-xs text-slate-500">最近检查：{date(s.last_checked_at)} · 列表获取成功：{date(s.last_success_at)} · {s.adapter === 'unverified' ? '候选来源，未完成接入验证' : '公开页面采集适配'}</p>{s.last_error && <p className="mt-2 text-sm text-amber-800">{s.last_error}</p>}</article>)}</div> : <Empty>暂无来源。可登记公开站点，或通过初始化命令载入待确认来源清单。</Empty>}</Panel>
    <Panel title="人工审计处置"><form className="grid gap-3 md:grid-cols-4" onSubmit={(e) => { e.preventDefault(); review.post(`${root}/runs/${review.data.runId}/review`, { preserveScroll: true }); }}><Field label="研究任务编号"><input className={inputClass} type="number" min="1" required value={review.data.runId} onChange={(e) => review.setData('runId', e.target.value)} /></Field><Field label="处置方式"><select className={inputClass} value={review.data.action} onChange={(e) => review.setData('action', e.target.value)}><option value="research">退回并重新研究</option><option value="withdraw">撤回结果</option></select></Field><Field label="核实意见与原因"><input className={inputClass} required value={review.data.note} onChange={(e) => review.setData('note', e.target.value)} /></Field><button className={`${primary} self-end`} disabled={review.processing}>记录处置</button></form><Errors errors={review.errors} /></Panel><Panel title="团队任务与审计">{runs.data.length ? <div className="flex flex-col gap-4">{runs.data.map((r) => <article key={r.id} className="rounded-lg border border-slate-200 p-4"><div className="flex flex-wrap items-center gap-3"><h3 className="min-w-0 grow break-all font-medium">#{r.id} {r.query || '来源采集'}</h3><Badge>{statuses[r.status] || r.status}</Badge><span className="text-xs text-slate-500">{stages[r.stage]} · 修正 {r.round}/2</span>{['queued', 'running'].includes(r.status) && <button className={secondary} onClick={() => router.post(`${root}/runs/${r.id}/cancel`)}>取消</button>}{r.status === 'failed' && <button className={secondary} onClick={() => router.post(`${root}/runs/${r.id}/retry`)}>重试</button>}</div>{r.error && <p className="mt-3 text-sm text-red-700">{r.error}</p>}{r.audit && <div className="mt-3 rounded-lg bg-slate-50 p-3 text-sm"><p>审计：{r.audit.decision}</p>{r.audit.issues?.map((issue, i) => <p key={i}>{issue}</p>)}{r.audit.manual_reviews?.map((review, i) => <p key={`review-${i}`}>人工处置：{review.note} · {date(review.at)}</p>)}</div>}{r.steps?.map((step) => <details className="mt-3 text-sm" key={step.id}><summary className="cursor-pointer">{stages[step.stage]} · {statuses[step.status] || step.status} · 尝试 {step.attempts} 次 · 输入 {step.usage?.prompt_tokens || 0} / 输出 {step.usage?.completion_tokens || 0} tokens</summary>{step.error && <p className="text-red-700">{step.error}</p>}<pre className="mt-2 max-h-80 overflow-auto whitespace-pre-wrap break-all rounded-lg bg-slate-50 p-3 text-xs">{JSON.stringify(step.output, null, 2)}</pre></details>)}</article>)}</div> : <Empty>暂无任务。启用来源或发起研究后，执行与审计记录会显示在这里。</Empty>}<div className="mt-4"><Pages links={runs.links} /></div></Panel></Shell>;
}
