import { router, useForm } from '@inertiajs/react';
import { useState } from 'react';
import { Shell, Panel, Field, Errors, Empty, Badge, root, inputClass, primary, secondary, statuses } from './shared';

const fields = { product: '产品与业务范围', qualifications: '资质与证明', valid_until: '资质有效期', capacity: '产能与交付能力', regions: '可服务地区', buyer: '采购主体', group_name: '集团（人工核实）', project_code: '历史项目编号', lot: '包件', amount: '历史金额及口径', unit: '数量单位', tax: '税费口径', freight: '运输范围', reference: '资料来源 / 证明说明', notes: '补充说明' };
const empty = { kind: 'capability', name: '', data: Object.fromEntries([...Object.keys(fields), 'outcome'].map((key) => [key, ''])) };
function template() {
    const csv = '\uFEFFkind,name,product,buyer,project_code,lot,outcome,amount,unit,tax,freight,reference,notes\n';
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' }));
    const link = document.createElement('a'); link.href = url; link.download = '独立业绩导入模板.csv'; link.click(); URL.revokeObjectURL(url);
}
export default function Company({ companies = [], preview }) {
    const [editing, setEditing] = useState(null);
    const form = useForm(empty);
    const upload = useForm({ file: null });
    function save(event) {
        event.preventDefault();
        const options = { preserveScroll: true, onSuccess: () => { form.setData(empty); setEditing(null); } };
        if (editing) form.put(`${root}/company/${editing}`, options); else form.post(`${root}/company`, options);
    }
    return <Shell title="独立企业资料"><p className="text-sm text-slate-500">这里的能力和业绩由管理员独立维护。确认后用于公司推荐；编辑后须重新确认。</p><Panel title={editing ? '修改资料' : '新增能力或历史业绩'}><form className="flex flex-col gap-4" onSubmit={save}><div className="grid gap-3 md:grid-cols-3"><Field label="资料类型"><select className={inputClass} value={form.data.kind} onChange={(e) => form.setData('kind', e.target.value)}><option value="capability">企业能力</option><option value="history">历史投标 / 成交业绩</option></select></Field><div className="md:col-span-2"><Field label="资料名称"><input className={inputClass} required value={form.data.name} onChange={(e) => form.setData('name', e.target.value)} /></Field></div></div><div className="grid gap-3 md:grid-cols-3">{Object.entries(fields).map(([key, label]) => <Field key={key} label={label}><input type={key === 'valid_until' ? 'date' : 'text'} className={inputClass} value={form.data.data[key] || ''} onChange={(e) => form.setData('data', { ...form.data.data, [key]: e.target.value })} /></Field>)}<Field label="历史投标结果"><select className={inputClass} value={form.data.data.outcome || ''} onChange={(e) => form.setData('data', { ...form.data.data, outcome: e.target.value })}><option value="">不适用 / 未知</option><option value="submitted">已递交</option><option value="won">已中标</option><option value="lost">未中标</option><option value="unknown">未知</option></select></Field></div><Errors errors={form.errors} /><div className="flex gap-3"><button className={primary} disabled={form.processing}>保存为待确认资料</button>{editing && <button className={secondary} type="button" onClick={() => { setEditing(null); form.setData(empty); }}>取消编辑</button>}</div></form></Panel>
    <Panel title="批量导入预览"><p className="mb-3 text-sm text-slate-500">UTF-8 CSV，最多 200 行。kind 填 capability 或 history；outcome 填 submitted、won、lost 或 unknown。上传只生成预览，确认后才入库。</p><form className="flex flex-wrap items-center gap-3" onSubmit={(e) => { e.preventDefault(); upload.post(`${root}/imports/preview`); }}><input aria-label="选择 CSV 文件" type="file" accept=".csv" required onChange={(e) => upload.setData('file', e.target.files[0])} /><button className={primary} disabled={upload.processing}>上传并预览</button><button className={secondary} type="button" onClick={template}>下载空白模板</button></form><Errors errors={upload.errors} />{preview && <div className="mt-4"><h3 className="font-semibold">预览 {preview.rows.length} 条资料</h3>{preview.errors.map((error, i) => <p role="alert" className="my-2 text-red-700" key={i}>{error}</p>)}<div className="my-3 max-h-80 overflow-auto"><table className="w-full text-sm"><thead><tr><th>类型</th><th>名称</th><th>内容</th></tr></thead><tbody>{preview.rows.map((row, i) => <tr key={i}><td>{row.kind}</td><td>{row.name}</td><td className="max-w-lg break-words">{Object.entries(row.data).filter(([, v]) => v).map(([k, v]) => `${fields[k] || k}：${v}`).join('；')}</td></tr>)}</tbody></table></div><button className={primary} disabled={!!preview.errors.length || !!preview.confirmed_at} onClick={() => router.post(`${root}/imports/${preview.id}/confirm`)}>{preview.confirmed_at ? '已导入' : '确认导入并用于分析'}</button></div>}</Panel>
    <Panel title="已维护的资料">{companies.length ? <div className="flex flex-col gap-3">{companies.map((company) => <article className="rounded-lg border border-slate-200 p-4" key={company.id}><div className="flex flex-wrap items-center gap-3"><h3 className="grow font-medium">{company.name}</h3><Badge>{company.kind === 'capability' ? '企业能力' : '历史业绩'}</Badge><Badge>{statuses[company.status]}</Badge><button className={secondary} onClick={() => { setEditing(company.id); form.setData({ kind: company.kind, name: company.name, data: company.data }); window.scrollTo({ top: 0, behavior: 'smooth' }); }}>编辑</button>{company.status !== 'confirmed' && <button className={primary} onClick={() => router.post(`${root}/company/${company.id}/confirm`)}>确认资料</button>}</div><p className="mt-3 text-sm leading-7 text-slate-600">{Object.entries(company.data).filter(([, value]) => value).map(([key, value]) => `${fields[key] || key}：${value}`).join('；')}</p></article>)}</div> : <Empty>暂无独立企业资料。资料不足时，系统不会推测我方能力与历史合作。</Empty>}</Panel></Shell>;
}
