import { Link, useForm, usePoll } from '@inertiajs/react';
import { Shell, Empty, Field, NoticeCard, Pages, inputClass, primary, kinds, date } from './shared';

export default function Index({ notices = { data: [] }, filters = {}, bookmarks = [], automation = {}, focusReport, briefings = [], canManage, hubLinks = {} }) {
    const form = useForm({ q: filters.q || '', region: filters.region || '', kind: filters.kind || '', sort: ['recommended', 'latest'].includes(filters.sort) ? filters.sort : 'recommended', history: filters.history === '1' || filters.history === true });
    usePoll(15000, { only: ['notices', 'automation'] });
    return <Shell title="为你推荐"><div className="rounded-xl bg-slate-900 p-6 text-white"><p className="mb-2 text-xs tracking-widest text-sky-200">招采信息中心</p><h2 className="text-2xl font-semibold">值得跟进的招采机会</h2><p className="mt-3 text-sm leading-7 text-slate-300">自动汇集公开公告，参考已有项目，为你整理跟进理由和采购分析。</p><div className="mt-5 flex flex-wrap gap-x-5 gap-y-2 text-xs text-sky-100"><span>{automation.sourceCount || 0} 个公开来源自动更新</span><span>{automation.projectCount ? `参考 ${automation.projectCount} 条可见项目主档` : '当前依据公开信息推荐'}</span>{automation.pending > 0 && <span role="status">{automation.pending} 项深度分析正在后台处理</span>}</div></div>
    {focusReport?.directions?.length > 0 && <section className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-center gap-2">{focusReport.directions.map((d) => <span key={d.label} className="rounded-full bg-sky-50 px-3 py-1.5 text-xs text-sky-800">{d.label}</span>)}</div><details className="mt-3 text-sm"><summary className="cursor-pointer text-slate-500">已根据 {focusReport.project_count} 条项目记录确定关注方向 · 查看依据</summary><div className="mt-4 grid gap-4 md:grid-cols-2">{focusReport.directions.map((d) => <div key={d.label} className="rounded-lg bg-slate-50 p-4"><h3 className="font-medium">{d.label} <span className="text-xs text-slate-500">· {d.count} 条参考记录</span></h3><p className="mt-2 text-sm leading-6 text-slate-600">{d.advice}</p><p className="mt-2 text-xs leading-6 text-slate-500">依据：{d.references.map((r) => r.title).join('、')}</p></div>)}</div><p className="mt-4 text-xs leading-6 text-slate-400">{focusReport.limitations}{focusReport.captured_at && ` · 线上主档读取于 ${date(focusReport.captured_at)}`}</p></details></section>}
    <form className="rounded-xl border border-slate-200 bg-white p-4" onSubmit={(e) => { e.preventDefault(); form.get(hubLinks.index || '/procurement-hub', { preserveState: true }); }}>
        <div className="flex gap-3"><input aria-label="搜索招采机会" className={inputClass} value={form.data.q} onChange={(e) => form.setData('q', e.target.value)} placeholder="搜索产品、采购单位或项目名称" /><button className={`${primary} shrink-0`} disabled={form.processing}>搜索</button></div>
        <details className="mt-3 text-sm text-slate-500"><summary className="cursor-pointer">更多筛选</summary><div className="mt-4 grid gap-3 sm:grid-cols-3"><Field label="地区"><input className={inputClass} value={form.data.region} onChange={(e) => form.setData('region', e.target.value)} placeholder="全部地区" /></Field><Field label="公告类型"><select className={inputClass} value={form.data.kind} onChange={(e) => form.setData('kind', e.target.value)}><option value="">全部类型</option>{Object.entries(kinds).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></Field><Field label="排序"><select className={inputClass} value={form.data.sort} onChange={(e) => form.setData('sort', e.target.value)}><option value="recommended">推荐优先</option><option value="latest">最新发布</option></select></Field><label className="hub-check flex items-center gap-2"><input type="checkbox" checked={form.data.history} onChange={(e) => form.setData('history', e.target.checked)} />包含已截止公告</label></div></details>
    </form>
    <div className="flex flex-wrap justify-between gap-2 text-sm text-slate-500"><span>{notices.total || 0} 条机会与采购动态</span><Link href={hubLinks.research || '/procurement-hub/research'} className="text-steel">专题研究与分析报告 →</Link></div>
    {notices.data.length ? notices.data.map((n) => <NoticeCard key={n.id} notice={n} briefing={briefings.find((b) => b.notice_id === n.id)} bookmarked={bookmarks.includes(n.id)} />) : <Empty>{filters.q ? '暂无匹配公告，可以换个关键词继续查找。' : '正在自动汇集公开公告，采集完成后会在这里展示，无需配置。'}</Empty>}<Pages links={notices.links} />
    <div className="flex flex-wrap justify-between gap-3 text-xs text-slate-400"><span>{automation.lastUpdated ? `最近收录：${date(automation.lastUpdated)}` : '来源可用性与分析进度由后台维护'}</span>{canManage && <Link href={hubLinks.admin || '/procurement-hub/admin'}>高级维护</Link>}</div>
    </Shell>;
}
