import { Link, router, usePoll } from '@inertiajs/react';
import { Shell, Panel, Badge, Report, Screening, Brief, root, kinds, date, safeUrl, primary, secondary } from './shared';

export default function Show({ notice, reports = [], pendingRun, briefing, screening, timeline = [], bookmarked }) {
    const primaryReport = reports.find((run) => run.status === 'published' && run.result);
    const historyReports = reports.filter((run) => run !== primaryReport);
    usePoll(10000, { only: ['reports', 'pendingRun'] });
    return <Shell title="公告详情"><Panel><div className="mb-3 flex flex-wrap gap-2"><Badge>{kinds[notice.kind]}</Badge><Badge>版本 {notice.revision}</Badge></div><h2 className="text-2xl font-semibold leading-relaxed">{notice.title}</h2>
    <dl className="mt-5 grid gap-4 text-sm md:grid-cols-3">{[['采购单位', notice.buyer], ['所属集团', notice.group_name ? `${notice.group_name}${notice.group_confirmed ? '' : '（待核实）'}` : null], ['项目编号 / 包件', [notice.project_code, notice.lot].filter(Boolean).join(' / ')], ['原文发布时间', notice.facts?.published_at_text || date(notice.published_at)], ['截止时间', date(notice.deadline)], ['产品 / 地区', [notice.product, notice.region].filter(Boolean).join(' / ')]].map(([label, value]) => <div key={label}><dt className="text-slate-500">{label}</dt><dd className="mt-1">{value || '未公开 / 待核实'}</dd></div>)}</dl>
    <div className="mt-5 flex flex-wrap gap-3"><a className={primary} href="#analysis">查看采购分析</a><button className={secondary} onClick={() => router.post(`${root}/notices/${notice.id}/bookmark`, {}, { preserveScroll: true })}>{bookmarked ? '取消收藏' : '收藏公告'}</button><Link className={secondary} href={root}>返回公告中心</Link></div></Panel>
    {screening && !primaryReport && <Screening value={screening} />}
    <section id="analysis" className="flex scroll-mt-4 flex-col gap-5">{primaryReport && <Report run={primaryReport} />}{pendingRun && <Report run={pendingRun} />}{briefing && (primaryReport ? <details className="rounded-xl border border-slate-200 bg-white p-4"><summary className="cursor-pointer text-sm font-medium">原文与主档核对</summary>{screening && <Screening value={screening} />}<div className="mt-4"><Brief value={briefing} /></div></details> : <Brief value={briefing} />)}{historyReports.length > 0 && <details className="rounded-xl border border-slate-200 bg-white p-4"><summary className="cursor-pointer text-sm font-medium">历史分析记录</summary><div className="mt-4 flex flex-col gap-4">{historyReports.map((run) => <Report key={run.id} run={run} />)}</div></details>}{!briefing && !pendingRun && !reports.length && <Panel title="采购分析"><p className="text-sm text-slate-500">后台正在整理原文与历史记录，结果完成后会自动显示。</p></Panel>}</section>
    <div className="grid gap-5 lg:grid-cols-3"><div className="flex min-w-0 flex-col gap-5 lg:col-span-2"><Panel title="采购与价格信息"><dl className="grid gap-3 text-sm md:grid-cols-2">{Object.entries({ procurement_content: '采购内容', procurement_scope: '原文采购类别', requirements: '资格条件', amount: '原文金额', currency: '原币种', deadline_text: '原文截止时间及口径', amount_type: '金额阶段', quantity: '数量', unit: '单位', spec: '规格', tax: '税费口径', freight: '运输范围', rental_period: '租赁期限', supplier: '公示供应商' }).map(([key, label]) => <div key={key}><dt className="text-slate-500">{label}</dt><dd>{key === 'amount_type' ? ({ budget: '预算', candidate: '候选人报价', award: '成交金额', contract: '合同金额', unknown: '待核实' }[notice.facts?.[key]] || '待核实') : (notice.facts?.[key] || (key === 'requirements' && briefing?.conditions?.length ? '请参考上方原文条件' : '尚未提取，请查看原文'))}</dd></div>)}</dl>{notice.missing?.length > 0 && <p className="mt-4 text-sm text-amber-800">待补充：{notice.missing.join('、')}</p>}</Panel>
    <Panel title="原文与版本证据">{notice.evidence?.map((e) => <details className="border-b border-slate-100 py-3" key={e.id}><summary className="cursor-pointer text-sm font-medium">证据 {e.id} · 获取于 {date(e.fetched_at)}</summary>{safeUrl(e.url) && <a className="my-3 inline-block text-sm text-steel underline" href={e.url} target="_blank" rel="noopener noreferrer">打开来源原文 ↗</a>}<pre className="max-h-96 overflow-auto whitespace-pre-wrap break-words rounded-lg bg-slate-50 p-4 text-sm leading-7">{e.text}</pre><div className="mt-3 flex flex-wrap gap-3">{e.attachments?.filter((a) => safeUrl(a.url)).map((a, i) => <a className="text-sm text-steel underline" key={i} href={a.url} target="_blank" rel="noopener noreferrer">{a.title || '原站附件'} · {a.status === 'fetched' ? '已留存证据' : a.status === 'unavailable' ? '获取失败' : '原站链接，未提取'} ↗</a>)}</div></details>)}</Panel></div>
    <Panel title="公告进展">{timeline.map((n) => <Link className="mb-4 block border-l-2 border-sky-200 pl-3 text-sm" key={n.id} href={`${root}/notices/${n.id}`}><p className="font-semibold">{kinds[n.kind]}</p><p className="my-1">{n.title}</p><p className="text-xs text-slate-500">{date(n.published_at)}</p></Link>)}<p className="text-xs leading-6 text-slate-500">只关联有足够依据的项目与包件；暂无关联记录不代表未发布后续公告。</p></Panel></div>
    </Shell>;
}
