<?php

$field = fn (string $key, string $label, string $type = 'text', array $extra = []) => array_merge([
    'key' => $key,
    'label' => $label,
    'type' => $type,
], $extra);
$code = fn (string $key, string $label) => $field($key, $label, 'readonly', ['system' => 'code']);
$relation = fn (string $key, string $label, string $target, array $extra = []) => $field($key, $label, 'relation', array_merge(['target' => $target], $extra));
$select = fn (string $key, string $label, array $options, array $extra = []) => $field($key, $label, 'select', array_merge(['options' => $options], $extra));
$date = fn (string $key, string $label, array $extra = []) => $field($key, $label, 'date', $extra);
$number = fn (string $key, string $label, array $extra = []) => $field($key, $label, 'number', $extra);
$file = fn (string $key, string $label, array $extra = []) => $field($key, $label, 'file', $extra);

$projectStages = ['合同录入', '技术确认', '正在对接', '采购执行', '生产加工', '成品发货', '对账回款', '项目完成', '异常', '设计出图', '发货签收'];
$projectStatuses = ['进行中', '预警', '暂停', '已完成', '已终止'];
$ownerRoles = ['业务', '技术', '采购', '生产', '财务', '库管', '厂长', '系统'];
$flowStatuses = ['草稿', '待审批', '已审批', '进行中', '已完成', '异常', '已关闭', '执行中', '待签收', '未签收', '已签收', '未回款', '部分回款', '已回款', '待收款', '已收款'];
$yesNoWarn = ['是', '否'];
$steelTypes = ['钢板', '槽钢', '方管'];
$steelCategories = ['钢板', '型钢', '管材'];
$materialModels = ['Q235', 'Q355', 'ER50-6', '待补充'];
$specSizes = ['6mm×1500×6000', '10#槽钢', '40×40方管', '待补充'];
$units = ['张', '根', 'kg', '吨', '桶', '盒'];
$bins = ['A区-01', 'B区-01', 'C区-01', 'F区-01', '待分配'];
$teams = ['班组A', '班组B', '班组C'];
$shopTeams = ['下料班组', '焊接班组', '装配班组', '维修班组', '待补充'];

return [
    'default_role' => 'basic',

    'roles' => [
        ['name' => 'basic', 'label' => '基础角色', 'description' => '默认注册角色：只看大盘和提交采购申请。', 'locked' => false],
        ['name' => 'admin', 'label' => '管理', 'description' => '系统管理、RBAC、全部对象权限。', 'locked' => true],
        ['name' => 'business', 'label' => '业务', 'description' => '客户、合同、项目推进。', 'locked' => false],
        ['name' => 'engineering', 'label' => '技术', 'description' => '图纸设计、图纸下放、请购。', 'locked' => false],
        ['name' => 'production', 'label' => '生产', 'description' => '生产任务、日报、拆解、发货、请购。', 'locked' => false],
        ['name' => 'procurement', 'label' => '采购', 'description' => '采购审批、采购日报、到货处理。', 'locked' => false],
        ['name' => 'warehouse', 'label' => '库管', 'description' => '库存、出入库、退料、废料、盘点。', 'locked' => false],
        ['name' => 'finance', 'label' => '财务', 'description' => '对账、开票、回款、应收风险。', 'locked' => false],
    ],

    'permissions' => [
        ['key' => 'dashboard.view', 'module' => 'dashboard', 'action' => 'view', 'label' => '查看大盘'],
        ['key' => 'requisition.create', 'module' => 'quick', 'action' => 'create', 'label' => '提交采购申请'],
        ['key' => 'rbac.manage', 'module' => 'system', 'action' => 'manage', 'label' => '管理用户与权限'],
    ],

    'role_permissions' => [
        'basic' => ['dashboard.view', 'requisition.create'],
        'admin' => ['*'],
        'business' => ['dashboard.view'],
        'engineering' => ['dashboard.view', 'requisition.create'],
        'production' => ['dashboard.view', 'requisition.create'],
        'procurement' => ['dashboard.view'],
        'warehouse' => ['dashboard.view', 'requisition.create'],
        'finance' => ['dashboard.view'],
    ],

    'objects' => [
        [
            'key' => 'customer', 'label' => '客户信息', 'group' => '主数据', 'code_prefix' => 'CUST', 'title_field' => 'name', 'roles' => ['business'],
            'fields' => [
                $code('customer_no', '客户编号'),
                $field('name', '客户名称', 'text', ['required' => true]),
                $field('contact', '联系人'),
                $field('phone', '联系电话'),
                $field('address', '地址'),
                $select('level', '客户等级', ['A', 'B', 'C']),
                $field('cooperation_history', '合作历史'),
                $field('remark', '备注'),
            ],
        ],
        [
            'key' => 'material', 'label' => '物料主档', 'group' => '主数据', 'code_prefix' => 'MAT', 'title_field' => 'name', 'roles' => ['procurement', 'warehouse'], 'write_roles' => ['warehouse'],
            'fields' => [
                $field('product_code', '产品编码'),
                $field('name', '产品名称', 'text', ['required' => true]),
                $field('spec_model', '规格型号'),
                $select('material_quality', '材质', $materialModels),
                $number('thickness', '厚度(mm)'),
                $number('width', '宽度(mm)'),
                $number('length', '长度(mm)'),
                $select('unit', '单位', $units),
                $number('unit_weight', '单重(kg)'),
                $number('safety_stock', '安全库存'),
                $field('default_supplier', '默认供应商'),
                $select('status', '产品状态', ['启用', '停用']),
                $field('remark', '备注'),
            ],
        ],
        [
            'key' => 'project', 'label' => '项目主档', 'group' => '主数据', 'code_prefix' => 'PRJ', 'title_field' => 'name', 'roles' => ['business', 'engineering', 'procurement', 'production', 'warehouse', 'finance'], 'write_roles' => ['business', 'finance'],
            'fields' => [
                $field('name', '项目名称', 'text', ['required' => true]),
                $relation('customer_id', '客户名称', 'customer'),
                $field('project_no', '项目编号'),
                $select('stage', '当前阶段', $projectStages),
                $select('overall_status', '总体状态', $projectStatuses),
                $field('related_contract_no', '关联合同编号', 'readonly'),
                $number('contract_amount', '合同金额'),
                $date('delivery_date', '交付日期'),
                $number('paid_amount', '回款金额'),
                $select('owner_role', '责任岗位', $ownerRoles),
                $field('remark', '备注'),
                $date('handover_date', '项目对接日期'),
                $field('manager', '业务经理'),
                $number('contract_qty', '合同数量'),
                $number('weight', '预估重量（吨）'),
                $number('signed_qty', '签收数量'),
                $number('shipped_qty', '发货数量'),
                $number('arrears', '欠款'),
                $field('invoiced_amount', '已开票金额', 'readonly'),
                $field('uninvoiced_amount', '未开票金额', 'readonly'),
                $date('last_payment_date', '末次回款日期'),
                $number('collection_count', '催款次数'),
                $field('risk', '当前风险点'),
            ],
        ],
        [
            'key' => 'contract', 'label' => '客户与合同', 'group' => '履约', 'code_prefix' => 'HT', 'title_field' => 'code', 'roles' => ['business'],
            'fields' => [
                $code('contract_no', '合同编号'),
                $select('status', '合同状态', ['已收到', '未收到']),
                $relation('project_id', '项目名称', 'project'),
                $field('project_no_norm', '项目编号（规范）'),
                $field('remark', '备注'),
                $relation('customer_id', '客户名称', 'customer', ['required' => true]),
                $select('ctype', '合同类型', ['销售合同', '加工合同', '补充协议']),
                $number('amount', '合同金额', ['required' => true]),
                $date('signed_date', '签订日期'),
                $field('business_owner', '业务负责人'),
                $field('contract_chase_record', '合同催要记录'),
                $number('contract_qty', '合同数量'),
            ],
        ],
        [
            'key' => 'drawing', 'label' => '技术图纸与方案', 'group' => '履约', 'code_prefix' => 'TZ', 'title_field' => 'name', 'roles' => ['engineering'],
            'fields' => [
                $field('drawing_no', '图纸编号'),
                $relation('project_id', '项目名称', 'project', ['required' => true]),
                $field('project_no_norm', '项目编号（规范）'),
                $field('manager', '业务经理'),
                $date('handover_date', '项目对接日期'),
                $field('name', '图纸名称（模板类型）', 'text', ['required' => true]),
                $field('designer', '设计人'),
                $date('drawing_date', '出图日期'),
                $select('design_status', '设计状态', $flowStatuses),
                $field('project_progress', '项目进度'),
                $select('release_status', '下放状态', ['未下放', '已下放']),
                $date('release_date', '下放日期'),
                $date('required_arrival_date', '对方要求到货日期'),
                $number('weight', '预估重量（吨）'),
                $number('release_price', '下放单价'),
                $field('receiver', '接收人'),
                $field('receiving_factory', '接收厂区'),
                $field('remark', '备注'),
                $file('attachment', '附件'),
            ],
        ],
        [
            'key' => 'work_order', 'label' => '生产任务', 'group' => '履约', 'code_prefix' => 'TASK', 'title_field' => 'code', 'roles' => ['production'],
            'fields' => [
                $code('task_no', '生产任务单编号'),
                $relation('project_id', '项目名称', 'project'),
                $field('project_no_norm', '项目编号（规范）'),
                $select('status', '任务状态', ['完成', '未完成', '部分完成']),
                $field('expected_materials', '预计用料'),
                $file('nesting_sheet', '排料单'),
                $field('remark', '备注'),
                $relation('drawing_id', '接收图纸编号', 'drawing'),
                $field('drawing_no', '图纸编号', 'readonly'),
                $field('drawing_name', '图纸名称', 'readonly'),
                $select('team', '加工班组', $teams),
                $date('plan_start_date', '计划开工日期'),
                $date('actual_start_date', '实际开工日期'),
                $select('material_ready_status', '原材料到位状态', ['未到位', '部分到位', '已到位']),
                $select('release_status', '任务下放状态', ['未下放', '已下放']),
                $select('production_owner', '生产负者人', ['武帅强', '王明', '赵魏俊', '秦晓前', '孙军', '车间主管']),
                $number('weight', '预估重量（吨）'),
                $number('progress', '状态进度'),
                $file('attachment', '附件'),
                $date('expected_finish_date', '预计完成日期'),
                $number('expected_loss', '预计料损'),
            ],
        ],
        [
            'key' => 'team_log', 'label' => '班组日报', 'group' => '履约', 'code_prefix' => 'DAILY', 'title_field' => 'code', 'roles' => ['production'],
            'fields' => [
                $code('daily_no', '日报编号'),
                $relation('project_id', '项目名称', 'project'),
                $field('project_no_norm', '项目编号（规范）'),
                $relation('work_order_id', '任务单号', 'work_order', ['required' => true]),
                $field('drawing_no', '图纸编号', 'readonly'),
                $number('progress', '状态进度'),
                $field('remark', '备注'),
                $date('work_date', '实际开始日期'),
                $select('team', '班组名称', $teams),
                $field('part_name', '加工产品/部件名称'),
                $number('estimated_weight', '预估重量(吨）'),
                $number('real_qty', '实际加工重量（吨）'),
                $select('production_owner', '生产负责人', ['孙军', '班组A负责人', '帅强', '王明', '维俊', '磊磊']),
                $field('material_name', '领用物资名称'),
                $field('material_spec', '物资规格'),
                $number('qty', '数量'),
                $number('tonnage', '吨位'),
                $file('attachment', '附件'),
            ],
        ],
        [
            'key' => 'teardown', 'label' => '拆解表', 'group' => '履约', 'code_prefix' => 'CJ', 'title_field' => 'code', 'roles' => ['production'],
            'fields' => [
                $code('record_no', '记录编号'),
                $relation('project_id', '项目名称', 'project'),
                $field('project_no_norm', '项目编号（规范）'),
                $field('drawing_no', '图纸编号'),
                $field('drawing_name', '图纸名称'),
                $date('teardown_date', '拆解日期'),
                $field('operator', '拆解人'),
                $select('material_ready_status', '原材料到位状态', ['未到位', '部分到位', '已到位']),
                $select('release_status', '任务下放状态', ['未下放', '已下放']),
                $date('release_date', '下放日期'),
                $date('plan_start_date', '计划开工日期'),
                $date('actual_start_date', '实际开工日期'),
                $field('remark', '备注'),
            ],
        ],
        [
            'key' => 'shipment', 'label' => '成品发货', 'group' => '履约', 'code_prefix' => 'SHIP', 'title_field' => 'code', 'roles' => ['production'],
            'fields' => [
                $code('shipment_no', '发货记录编号'),
                $relation('project_id', '项目名称', 'project', ['required' => true]),
                $field('project_no_norm', '项目编号（规范）'),
                $field('remark', '备注'),
                $field('product_name', '成品名称'),
                $file('attachment', '附件'),
                $number('qty_ton', '发货数量（吨）'),
                $date('ship_date', '发货日期'),
                $field('shipping_owner', '发货负责人'),
                $field('logistics_info', '物流信息'),
                $field('plate_no', '车牌号'),
                $field('driver_phone', '司机联系方式'),
            ],
        ],
        [
            'key' => 'receivable', 'label' => '对账回款', 'group' => '履约', 'code_prefix' => 'AR', 'title_field' => 'code', 'roles' => ['finance'],
            'fields' => [
                $code('receivable_no', '对账编号'),
                $field('customer_name', '客户名称'),
                $relation('project_id', '项目名称', 'project'),
                $field('project_no_norm', '项目编号（规范）'),
                $select('pay_status', '回款状态', $flowStatuses),
                $field('remark', '备注'),
                $field('contract_no', '关联合同编号'),
                $number('signed_qty', '累计签收数量'),
                $number('actual_amount', '实际发生金额'),
                $date('actual_amount_updated_at', '实际发生金额更新日期'),
                $number('paid_amount', '回款金额'),
                $number('unpaid', '未收款'),
                $number('reconciled_amount', '累计对账金额'),
                $date('reconcile_date', '对账日期'),
                $number('invoice_amount', '累计开票金额'),
                $number('uninvoiced_amount', '未开票金额'),
                $number('contract_amount', '合同金额'),
                $number('payment_progress', '回款进度'),
                $date('last_payment_date', '末次回款日期'),
                $select('hang_status', '挂账状态', ['未挂账', '已挂账']),
                $select('invoice_status', '开票状态', ['未开票', '部分开票', '已开票']),
            ],
        ],
        [
            'key' => 'invoice', 'label' => '开票记录', 'group' => '履约', 'code_prefix' => 'INV', 'title_field' => 'code', 'roles' => ['finance'],
            'fields' => [
                $relation('customer_id', '客户', 'customer'),
                $relation('project_id', '项目', 'project', ['required' => true]),
                $field('invoice_no', '发票号码'),
                $number('amount', '开票金额', ['required' => true]),
                $date('invoice_date', '开票日期'),
                $select('status', '开票状态', ['待开票', '已开票', '已作废']),
                $file('attachment', '发票附件'),
            ],
        ],
        [
            'key' => 'purchase', 'label' => '采购日报', 'group' => '采购库存', 'code_prefix' => 'CG', 'title_field' => 'code', 'roles' => ['procurement'],
            'fields' => [
                $date('date', '日期'),
                $relation('project_id', '采购项目', 'project'),
                $field('requester', '发起人'),
                $relation('material_id', '材料名称', 'material'),
                $field('spec', '规格'),
                $field('reported_qty', '上报数量'),
                $number('tonnage', '对应吨位'),
                $date('purchase_date', '采购日期'),
                $select('supplier_name', '供应商名称', ['上海某钢材有限公司', '杭州某金属材料有限公司', '齐心', '太钢大明', '钢乾盛世', '天津震翔', '中钢网']),
                $number('qty', '最终采购数量'),
                $field('price', '单价'),
                $field('total_price', '总价'),
                $select('arrived', '材料是否到货', ['未到货', '已到货', '部分到货']),
                $select('daily_status', '单日采购状态', ['已采购', '未采购', '部分采购']),
                $date('expected_arrival_date', '预计到货日期'),
                $field('actual_arrival_date', '实际到货日期'),
                $field('remark', '备注'),
                $field('task_id', '任务ID'),
            ],
        ],
        [
            'key' => 'requisition', 'label' => '采购申请（请购单）', 'group' => '采购库存', 'code_prefix' => 'QG', 'title_field' => 'code', 'roles' => ['procurement', 'warehouse', 'production', 'engineering'], 'write_roles' => ['procurement'],
            'fields' => [
                $select('requester', '需求方', ['生产', '技术', '库管', '业务'], ['required' => true]),
                $relation('material_id', '物料', 'material', ['required' => true]),
                $number('qty', '需求数量', ['required' => true]),
                $select('unit', '单位', $units),
                $relation('project_id', '关联项目', 'project'),
                $select('urgency', '紧急程度', ['普通', '紧急', '特急']),
                $field('reason', '原因'),
                $select('status', '状态', ['待处理', '已转采购', '已驳回']),
            ],
        ],
        [
            'key' => 'material_request', 'label' => '领料申请', 'group' => '采购库存', 'code_prefix' => 'LL', 'title_field' => 'code', 'roles' => ['production', 'warehouse'], 'write_roles' => ['warehouse'],
            'fields' => [
                $field('requester', '申请人/部门', 'text', ['required' => true]),
                $relation('material_id', '物料', 'material', ['required' => true]),
                $relation('project_id', '项目', 'project'),
                $number('qty', '申请数量', ['required' => true]),
                $select('unit', '单位', $units),
                $select('team', '班组', $shopTeams),
                $date('apply_date', '申请日期'),
                $field('reason', '用途'),
                $select('status', '状态', ['待审批', '已出库', '已驳回']),
                $relation('outbound_id', '出库单', 'outbound'),
            ],
        ],
        [
            'key' => 'inbound', 'label' => '原材料入库单', 'group' => '采购库存', 'code_prefix' => 'RK', 'title_field' => 'code', 'roles' => ['warehouse'],
            'fields' => [
                $code('inbound_no', '入库单号'),
                $field('supplier', '供应商'),
                $select('spec', '规格尺寸', $specSizes),
                $select('bin', '库位', $bins),
                $select('handler_sign', '经办签字', ['库管', '验收人', '采购', '送货方', '待签字']),
                $relation('material_id', '物资名称', 'material', ['required' => true]),
                $select('material_model', '材质/型号', $materialModels),
                $select('unit', '单位', $units),
                $number('qty', '数量/重量', ['required' => true]),
                $date('in_date', '入库日期'),
            ],
        ],
        [
            'key' => 'outbound', 'label' => '生产领料出库单', 'group' => '采购库存', 'code_prefix' => 'CK', 'title_field' => 'code', 'roles' => ['warehouse'],
            'fields' => [
                $code('outbound_no', '领料单号'),
                $select('bin', '库位', $bins),
                $select('prefer_scrap', '是否优先使用余料', $yesNoWarn),
                $select('approver', '审批人', ['主管', '计划负责人', '仓储负责人', '待审批']),
                $number('qty', '申请数量', ['required' => true]),
                $select('receiver', '领料人', ['领料人', '班组长', '待签字']),
                $select('stock_deducted', '库存是否已扣减', $yesNoWarn),
                $select('material_model', '材质/型号', $materialModels),
                $date('apply_date', '申请日期'),
                $select('spec', '规格尺寸', $specSizes),
                $number('real_qty', '实发数量'),
                $field('project_order_process', '项目/订单/工序'),
                $select('team', '班组', $shopTeams),
                $select('warehouse_keeper', '库管', ['库管', '仓储负责人', '待签字']),
                $relation('material_id', '物资名称', 'material', ['required' => true]),
                $select('unit', '单位', $units),
            ],
        ],
        [
            'key' => 'return_order', 'label' => '原材料退料单', 'group' => '采购库存', 'code_prefix' => 'TL', 'title_field' => 'code', 'roles' => ['warehouse'],
            'fields' => [
                $number('weight', '重量', ['required' => true]),
                $select('steel_category', '钢材类别', $steelCategories, ['required' => true]),
            ],
        ],
        [
            'key' => 'scrap_ledger', 'label' => '废料台账', 'group' => '采购库存', 'code_prefix' => 'FL', 'title_field' => 'code', 'roles' => ['warehouse'],
            'fields' => [
                $select('material_category', '物资', $steelTypes),
                $date('scrap_date', '日期'),
                $field('laser_team', '激光班组'),
                $field('unit', '单位'),
                $field('spec', '规格'),
                $number('qty', '数量'),
                $number('raw_weight', '原材重量'),
                $number('scrap_weight', '废料重量'),
                $number('loss_rate', '当日料损比'),
                $number('outbound_total', '当日出库单总量'),
            ],
        ],
        [
            'key' => 'scrap_quarter_stat', 'label' => '废料季度统计', 'group' => '采购库存', 'code_prefix' => 'FLQ', 'title_field' => 'stat_time', 'roles' => ['warehouse'], 'read_only' => true,
            'fields' => [
                $field('stat_time', '统计时间', 'readonly'),
                $relation('material_id', '物资', 'material'),
                $field('scrap_weight', '废料重量', 'readonly'),
                $field('avg_loss_rate', '本季度平均废料损比', 'readonly'),
            ],
        ],
        [
            'key' => 'stock_ledger', 'label' => '库存台账', 'group' => '采购库存', 'code_prefix' => 'KC', 'title_field' => 'code', 'roles' => ['warehouse'],
            'fields' => [
                $code('material_code', '物资编码'),
                $date('updated_date', '最后更新日期'),
                $number('in_qty', '本期入库'),
                $select('material_model', '材质/型号', $materialModels),
                $select('below_warn', '是否低于预警', $yesNoWarn),
                $select('spec', '规格尺寸', $specSizes),
                $relation('material_id', '物资名称', 'material', ['required' => true]),
                $number('balance_weight', '结存重量kg'),
                $number('balance', '结存数量'),
                $select('bin', '库位', $bins),
                $number('minimum_stock', '最低库存'),
                $select('category', '类别', $steelCategories),
                $number('opening', '期初数量'),
                $number('out_qty', '本期出库'),
                $select('unit', '单位', $units),
                $number('ret_qty', '本期退库'),
            ],
        ],
        [
            'key' => 'stocktake', 'label' => '盘点表', 'group' => '采购库存', 'code_prefix' => 'PD', 'title_field' => 'code', 'roles' => ['warehouse'],
            'fields' => [
                $code('stocktake_no', '盘点单号'),
                $select('handle_status', '处理状态', ['未处理', '处理中', '已完成', '需复盘']),
                $select('diff_reason', '差异原因', ['无', '漏记', '错发', '规格混放', '余料未登记', '现场占用']),
                $relation('material_id', '物资编码/名称', 'material'),
                $number('book_qty', '账面数量'),
                $select('checker', '盘点人', ['盘点人', '库管', '财务', '主管', '待签字']),
                $select('handle_suggestion', '处理意见', ['无', '补单', '调整库位', '追责', '报损', '复盘整改']),
                $select('material_spec', '材质规格', $specSizes),
                $number('real_qty', '实盘数量'),
                $date('stocktake_date', '盘点日期'),
                $select('reviewer', '复核人', ['复核人', '财务', '主管', '仓储负责人', '待签字']),
                $number('diff_weight', '巾异重量kg'),
                $select('stocktake_type', '盘点类型', ['日常抽盘', '月度盘点', '专项盘点', '年度盘点']),
                $number('diff_qty', '差异数量'),
            ],
        ],
    ],
];
