<?php

$field = fn (string $key, string $label, string $type = 'text', array $extra = []) => array_merge([
    'key' => $key,
    'label' => $label,
    'type' => $type,
], $extra);
$code = fn (string $key, string $label) => $field($key, $label, 'readonly', ['system' => 'code']);
$relation = fn (string $key, string $label, string $target, array $extra = []) => $field($key, $label, 'relation', array_merge(['target' => $target], $extra));
$multirelation = fn (string $key, string $label, string $target, array $extra = []) => $field($key, $label, 'multirelation', array_merge(['target' => $target], $extra));
$multiaccount = fn (string $key, string $label, array $extra = []) => $field($key, $label, 'multiaccount', $extra);
$creatableRelation = fn (string $key, string $label, string $target, array $extra = []) => $field($key, $label, 'creatable_relation', array_merge(['target' => $target], $extra));
$select = fn (string $key, string $label, array $options, array $extra = []) => $field($key, $label, 'select', array_merge(['options' => $options], $extra));
$date = fn (string $key, string $label, array $extra = []) => $field($key, $label, 'date', $extra);
$datetime = fn (string $key, string $label, array $extra = []) => $field($key, $label, 'datetime', $extra);
$number = fn (string $key, string $label, array $extra = []) => $field($key, $label, 'number', $extra);
$file = fn (string $key, string $label, array $extra = []) => $field($key, $label, 'file', $extra);
$files = fn (string $key, string $label, array $extra = []) => $field($key, $label, 'files', $extra);
$projectStatuses = ['投标中', '已中标', '已拿到加工函', '合同签署', '已完成'];
$units = ['张', '支', '根', 'kg', '吨', '桶', '盒'];

return [
    'default_role' => 'basic',
    'tender_timezone' => env('TENDER_TIMEZONE', 'Asia/Shanghai'),
    'retired_roles' => ['warehouse'],

    'roles' => [
        ['name' => 'basic', 'label' => '基础角色', 'description' => '默认注册角色：只看大盘和提交采购申请。', 'locked' => false],
        ['name' => 'admin', 'label' => '管理', 'description' => '系统管理、RBAC、全部对象权限。', 'locked' => true],
        ['name' => 'business', 'label' => '业务', 'description' => '客户、合同和项目推进。', 'locked' => false],
        ['name' => 'engineering', 'label' => '技术', 'description' => '图纸设计、拆解和请购；不访问项目主档。', 'locked' => false],
        ['name' => 'procurement', 'label' => '采购', 'description' => '采购申请、采购单和到货处理。', 'locked' => false],
        ['name' => 'production_manager', 'label' => '生产负责人', 'description' => '维护生产班组、成员和生产信息。', 'locked' => false],
        ['name' => 'production', 'label' => '生产', 'description' => '查看班组档案并填写生产信息。', 'locked' => false],
        ['name' => 'finance', 'label' => '财务', 'description' => '项目财务台账、开票和回款。', 'locked' => false],
        ['name' => 'tender', 'label' => '招投标', 'description' => '维护招投标信息并参与客户前期对接。', 'locked' => false],
    ],

    'permissions' => [
        ['key' => 'dashboard.view', 'module' => 'dashboard', 'action' => 'view', 'label' => '查看大盘'],
        ['key' => 'requisition.create', 'module' => 'quick', 'action' => 'create', 'label' => '提交采购申请'],
        ['key' => 'ai.harness.view', 'module' => 'ai', 'action' => 'view', 'label' => '使用 AI 数据助手'],
        ['key' => 'rbac.manage', 'module' => 'system', 'action' => 'manage', 'label' => '管理用户与权限'],
    ],

    'role_permissions' => [
        'basic' => ['dashboard.view', 'requisition.create', 'ai.harness.view'],
        'admin' => ['*'],
        'business' => ['dashboard.view', 'ai.harness.view'],
        'engineering' => ['dashboard.view', 'requisition.create', 'ai.harness.view'],
        'procurement' => ['dashboard.view', 'ai.harness.view'],
        'production_manager' => ['dashboard.view', 'requisition.create', 'ai.harness.view'],
        'production' => ['dashboard.view', 'requisition.create', 'ai.harness.view'],
        'finance' => ['dashboard.view', 'ai.harness.view'],
        'tender' => [
            'dashboard.view',
            'ai.harness.view',
            'object.customer.view',
            'object.customer.create',
            'object.customer.update',
        ],
    ],

    'objects' => [
        [
            'key' => 'customer', 'label' => '客户信息', 'group' => '主数据', 'code_prefix' => 'CUST', 'title_field' => 'name', 'roles' => ['business', 'finance'], 'write_roles' => ['business'],
            'fields' => [
                $code('customer_no', '客户编号'),
                $field('name', '客户名称', 'text', ['required' => true]),
                $field('address', '地址'),
                $select('level', '客户等级', ['A', 'B', 'C']),
                $field('cooperation_history', '合作历史'),
                $field('remark', '备注'),
            ],
        ],
        [
            'key' => 'customer_contact', 'label' => '客户联系人', 'group' => '主数据', 'code_prefix' => 'CONTACT', 'title_field' => 'name', 'roles' => ['business'],
            'fields' => [
                $field('name', '联系人姓名', 'text', ['required' => true]),
                $field('phone', '联系电话'),
                $relation('customer_id', '所属客户', 'customer', ['required' => true]),
                $multirelation('project_ids', '关联项目', 'project', ['readonly' => true]),
            ],
        ],
        [
            'key' => 'tender', 'label' => '招投标信息', 'group' => '招投标', 'code_prefix' => 'ZB', 'title_field' => 'name', 'roles' => ['tender', 'business'], 'write_roles' => ['tender'],
            'fields' => [
                $code('tender_no', '招投标编号'),
                $field('name', '标的名称', 'text', ['required' => true]),
                $creatableRelation('customer_id', '客户名称', 'customer', ['required' => true]),
                $field('tender_agency', '招标单位/代理机构'),
                $field('source_site', '信息来源网站'),
                $date('announce_date', '公告日期'),
                $datetime('register_deadline', '报名截止时间', ['required' => true]),
                $datetime('purchase_deadline', '购买标书截止时间', ['required' => true]),
                $datetime('submit_deadline', '投标截止时间', ['required' => true]),
                $datetime('bid_open_at', '开标时间'),
                $number('budget_amount', '预算金额', ['min' => 0]),
                $number('doc_fee', '标书费用', ['min' => 0]),
                $select('purchase_status', '标书购买状态', ['未购买', '已购买'], ['default' => '未购买']),
                $select('status', '招投标状态', ['跟踪中', '已报名', '已购标书', '制作中', '已递交', '已中标', '未中标', '已放弃'], [
                    'default' => '跟踪中',
                    'restricted_options' => ['已中标'],
                ]),
                $file('tender_file', '招标文件'),
                $file('bid_file', '投标文件扫描件'),
                $relation('converted_project_id', '流转项目', 'project', ['readonly' => true]),
                $field('manager', '投标负责人'),
            ],
        ],
        [
            'key' => 'material', 'label' => '物料主档', 'group' => '采购管理', 'code_prefix' => 'MAT', 'title_field' => 'name', 'roles' => ['procurement'], 'write_roles' => ['procurement'],
            'fields' => [
                $code('material_code', '材料编码'),
                $field('name', '物资名称', 'text', ['required' => true]),
                $field('spec', '材料规格'),
                $number('length_mm', '长度mm', ['min' => 0]),
                $number('width_mm', '宽度mm', ['min' => 0]),
                $select('status', '启用状态', ['启用', '停用'], ['default' => '启用']),
                $select('unit_weight_type', '单位重量类型', ['每平米', '每米', '每张', '每支']),
                $number('unit_weight', '单位重量', ['min' => 0]),
                $field('remark', '备注'),
            ],
        ],
        [
            'key' => 'production_team', 'label' => '生产班组', 'group' => '生产管理', 'code_prefix' => 'TEAM', 'title_field' => 'name', 'roles' => ['production_manager', 'production'], 'write_roles' => ['production_manager'],
            'fields' => [
                $code('team_no', '班组编号'),
                $field('name', '班组名称', 'text', ['required' => true]),
                $select('factory', '厂区', ['一厂', '二厂']),
                $relation('leader_id', '班组负责人', 'team_member'),
                $select('status', '启用状态', ['启用', '停用'], ['default' => '启用']),
                $field('remark', '备注'),
            ],
        ],
        [
            'key' => 'team_member', 'label' => '班组成员', 'group' => '生产管理', 'code_prefix' => 'MEM', 'title_field' => 'name', 'roles' => ['production_manager', 'production'], 'write_roles' => ['production_manager'],
            'fields' => [
                $code('member_no', '成员编号'),
                $field('name', '姓名', 'text', ['required' => true]),
                $relation('team_id', '所属班组', 'production_team', ['required' => true]),
                $select('status', '启用状态', ['启用', '停用'], ['default' => '启用']),
                $field('remark', '备注'),
            ],
        ],
        [
            'key' => 'project', 'label' => '业务项目', 'group' => '业务与合同', 'code_prefix' => 'XYC', 'title_field' => 'name', 'roles' => ['business', 'finance'], 'write_roles' => ['business', 'finance'],
            'fields' => [
                $field('name', '项目名称', 'text', ['required' => true]),
                $multirelation('customer_contact_ids', '客户联系人', 'customer_contact'),
                $relation('customer_id', '客户名称', 'customer', ['required' => true]),
                $code('project_no', '项目编号'),
                $field('business_owner_user_id', '负责业务员', 'account'),
                $multiaccount('informed_business_user_ids', '知会人员'),
                $select('overall_status', '总体状态', $projectStatuses, ['default' => '投标中']),
                $field('contract_status', '合同状态', 'readonly'),
                $date('first_shipment_date', '首次发货日期'),
                $date('last_shipment_date', '末次发货日期'),
                $field('remark', '备注'),
                $date('handover_date', '项目对接日期'),
                $field('contract_qty', '合同数量', 'readonly'),
                $number('weight', '合同重量（吨）'),
                $number('signed_weight', '累计签收重量', ['min' => 0]),
                $number('contract_amount', '合同金额', ['min' => 0]),
                $number('occurred_amount', '已发生金额', ['min' => 0]),
                $number('paid_amount', '已回款金额', ['min' => 0]),
                $date('last_payment_date', '末次回款日期'),
                $number('unpaid_amount', '未回款金额', ['min' => 0]),
                $number('reconciled_amount', '对账金额', ['min' => 0]),
                $number('invoiced_amount', '开票金额', ['min' => 0]),
                $number('uninvoiced_amount', '未开票金额', ['min' => 0]),
                $number('payment_progress', '回款进度', ['min' => 0, 'max' => 100]),
                $select('payment_status', '回款状态', ['未回款', '部分回款', '已回款']),
                $field('collection_count', '催款次数', 'readonly'),
                $field('risk', '当前风险点'),
            ],
        ],
        [
            'key' => 'contract', 'label' => '合同表', 'group' => '业务与合同', 'code_prefix' => 'HT', 'title_field' => 'code', 'roles' => ['business'], 'write_roles' => [],
            'fields' => [
                $code('contract_no', '合同编号'),
                $relation('customer_id', '客户', 'customer', ['required' => true]),
                $relation('project_id', '项目名称', 'project', ['required' => true]),
                $field('project_no', '项目编号', 'readonly'),
                $select('status', '合同状态', ['未签署', '已有加工函', '已签署'], ['default' => '未签署']),
                $select('ctype', '合同类型', ['销售合同', '加工合同', '补充协议']),
                $number('amount', '合同金额', ['required' => true]),
                $date('signed_date', '签订日期'),
                $files('processing_letter_attachments', '加工函附件'),
                $files('contract_attachments', '合同附件'),
                $files('statement_attachments', '对账单附件'),
                $field('contract_chase_record', '合同催要记录'),
                $number('contract_qty', '合同数量'),
                $field('remark', '备注'),
            ],
        ],
        [
            'key' => 'drawing', 'label' => '技术图纸与方案', 'group' => '履约', 'code_prefix' => 'TZ', 'title_field' => 'name', 'roles' => ['engineering'],
            'fields' => [
                $code('drawing_no', '图纸编号'),
                $relation('project_id', '项目名称', 'project', ['required' => true]),
                $field('project_no', '项目编号', 'readonly'),
                $field('manager', '业务经理'),
                $date('handover_date', '项目对接日期'),
                $field('name', '图纸名称（模板类型）', 'text', ['required' => true]),
                $field('designer', '设计人'),
                $date('drawing_date', '出图日期'),
                $select('design_status', '设计状态', ['草稿', '进行中', '已下放'], ['default' => '草稿']),
                $field('project_progress', '项目进度'),
                $field('release_date', '下放日期', 'readonly'),
                $date('required_arrival_date', '对方要求到货日期'),
                $number('weight', '预估重量（吨）'),
                $number('release_price', '下放单价'),
                $field('receiver', '接收人'),
                $field('receiving_factory', '接收厂区'),
                $field('remark', '备注'),
                $file('attachment', '附件'),
            ],
        ],
        [
            'key' => 'work_order', 'label' => '生产任务', 'group' => '生产管理', 'code_prefix' => 'TASK', 'title_field' => 'code', 'roles' => ['production_manager', 'production'],
            'fields' => [
                $code('task_no', '生产任务单编号'),
                $relation('project_id', '项目名称', 'project', ['readonly' => true]),
                $field('project_no', '项目编号', 'readonly'),
                $select('status', '任务状态', ['未开始', '生产中', '异常暂停', '已完成'], ['default' => '未开始']),
                $field('task_type', '任务类型'),
                $field('expected_material', '预计用料'),
                $file('nesting_sheet', '排料单'),
                $field('remark', '备注'),
                $relation('drawing_id', '接收图纸编号', 'drawing', ['required' => true]),
                $field('drawing_name', '图纸名称', 'readonly'),
                $relation('team_id', '加工班组', 'production_team'),
                $field('team_leader_name', '班组负责人', 'readonly'),
                $date('plan_start_date', '计划开工日期'),
                $date('actual_start_date', '实际开工日期'),
                $select('material_ready_status', '原材料到位状态', ['未到位', '部分到位', '已到位']),
                $select('release_status', '任务下放状态', ['未下放', '已下放'], ['default' => '未下放']),
                $relation('production_owner_id', '生产负责人', 'team_member'),
                $number('weight', '预估重量（吨）', ['min' => 0]),
                $number('production_qty_ton', '生产量（吨）', ['min' => 0]),
                $file('attachment', '附件'),
                $date('expected_finish_date', '预计完成日期'),
            ],
        ],
        [
            'key' => 'team_log', 'label' => '现场报工', 'group' => '生产管理', 'code_prefix' => 'REPORT', 'title_field' => 'code', 'roles' => ['production_manager', 'production'],
            'fields' => [
                $code('report_no', '报工编号'),
                $relation('project_id', '项目名称', 'project', ['required' => true]),
                $field('project_no', '项目编号', 'readonly'),
                $relation('team_id', '班组名称', 'production_team', ['required' => true]),
                $field('team_leader_name', '班组负责人', 'readonly'),
                $select('status', '生产状态', ['开始生产', '生产中', '异常暂停', '完成任务'], ['required' => true]),
                $select('process', '当前工序', ['切割', '焊接', '总装', '打磨', '其他'], ['required' => true]),
                $number('completed_qty', '本次完成数量', ['min' => 0]),
                $select('unit', '单位', ['件', '套', 'kg', '吨', '张', '根']),
                $select('exception_type', '异常类型', ['无', '缺料', '图纸问题', '设备故障', '质量问题', '人员不足', '其他'], ['default' => '无']),
                $date('work_date', '报工日期'),
                $field('part_name', '加工产品/部件名称'),
                $field('remark', '备注'),
                $file('attachment', '现场照片'),
            ],
        ],
        [
            'key' => 'teardown', 'label' => '拆解表', 'group' => '履约', 'code_prefix' => 'CJ', 'title_field' => 'code', 'roles' => ['production_manager', 'production'],
            'fields' => [
                $code('record_no', '记录编号'),
                $relation('drawing_id', '图纸编号', 'drawing', ['required' => true]),
                $field('drawing_name', '图纸名称', 'readonly'),
                $relation('project_id', '项目名称', 'project', ['readonly' => true]),
                $field('project_no', '项目编号', 'readonly'),
                $date('teardown_date', '拆解日期'),
                $date('teardown_finished_at', '拆解完成时间'),
                $field('operator', '拆解人'),
                $select('material_ready_status', '原材料到位状态', ['未到位', '部分到位', '已到位']),
                $date('plan_start_date', '计划开工日期'),
                $date('actual_start_date', '实际开工日期'),
                $field('remark', '备注'),
            ],
        ],
        [
            'key' => 'shipment', 'label' => '成品发货', 'group' => '履约', 'code_prefix' => 'SHIP', 'title_field' => 'code', 'roles' => ['production_manager', 'production'],
            'fields' => [
                $code('shipment_no', '发货记录编号'),
                $relation('project_id', '项目名称', 'project', ['required' => true]),
                $field('project_no', '项目编号', 'readonly'),
                $field('remark', '备注'),
                $field('product_name', '成品名称'),
                $file('attachment', '附件'),
                $number('qty_ton', '发货数量（吨）'),
                $date('ship_date', '发货日期'),
                $field('shipping_owner', '发货负责人'),
                $field('logistics_info', '物流信息'),
                $field('plate_no', '车牌号'),
                $field('driver_phone', '司机联系方式'),
            ],
        ],
        [
            'key' => 'receivable', 'label' => '项目财务台账', 'group' => '履约', 'code_prefix' => 'AR', 'title_field' => 'code', 'roles' => ['finance'],
            'fields' => [
                $code('receivable_no', '对账编号'),
                $relation('customer_id', '客户名称', 'customer', ['required' => true]),
                $relation('project_id', '项目名称', 'project', ['required' => true]),
                $field('project_no', '项目编号', 'readonly'),
                $select('pay_status', '回款状态', ['未回款', '部分回款', '已回款'], ['default' => '未回款']),
                $field('remark', '备注'),
                $number('signed_weight', '累计签收重量'),
                $number('occurred_amount', '实际发生金额'),
                $date('occurred_amount_updated_at', '实际发生金额更新日期'),
                $number('paid_amount', '已回款金额'),
                $number('unpaid_amount', '未回款金额'),
                $number('reconciled_amount', '对账金额'),
                $date('reconcile_date', '对账日期'),
                $number('invoiced_amount', '开票金额'),
                $number('uninvoiced_amount', '未开票金额'),
                $number('contract_amount', '合同金额'),
                $number('payment_progress', '回款进度'),
                $date('last_payment_date', '最后回款日期'),
            ],
        ],
        [
            'key' => 'invoice', 'label' => '开票记录', 'group' => '履约', 'code_prefix' => 'INV', 'title_field' => 'code', 'roles' => ['finance'],
            'fields' => [
                $relation('customer_id', '客户', 'customer'),
                $relation('project_id', '项目', 'project', ['required' => true]),
                $field('invoice_no', '发票号码'),
                $number('amount', '开票金额', ['required' => true]),
                $date('invoice_date', '开票日期'),
                $select('status', '开票状态', ['待开票', '已开票', '已作废']),
                $file('attachment', '发票附件'),
            ],
        ],
        [
            'key' => 'purchase', 'label' => '采购执行', 'group' => '采购管理', 'code_prefix' => 'CG', 'title_field' => 'code', 'roles' => ['procurement'],
            'fields' => [
                $date('date', '日期'),
                $relation('project_id', '采购项目', 'project'),
                $field('requester', '发起人'),
                $relation('material_id', '材料名称', 'material', ['scope' => 'item', 'required' => true]),
                $field('material_model', '材质/型号', 'text', ['scope' => 'item']),
                $field('spec', '规格', 'text', ['scope' => 'item']),
                $field('reported_qty', '上报数量', 'text', ['scope' => 'item']),
                $date('purchase_date', '采购日期'),
                $field('supplier_name', '供应商名称'),
                $number('qty', '最终采购数量', ['scope' => 'item', 'required' => true, 'min' => 0]),
                $number('weight_ton', '重量（吨）', ['scope' => 'item', 'min' => 0]),
                $select('unit', '单位', $units, ['scope' => 'item']),
                $number('price', '单价', ['scope' => 'item', 'min' => 0]),
                $number('total_price', '总价', ['scope' => 'item', 'min' => 0]),
                $select('arrived', '材料是否到货', ['未到货', '已到货', '部分到货'], ['scope' => 'item']),
                $select('daily_status', '单日采购状态', ['已采购', '未采购', '部分采购'], ['scope' => 'item']),
                $date('expected_arrival_date', '预计到货日期', ['scope' => 'item']),
                $date('actual_arrival_date', '实际到货日期', ['scope' => 'item']),
                $field('remark', '备注', 'text', ['scope' => 'item']),
                $code('task_id', '任务ID'),
            ],
        ],
        [
            'key' => 'requisition', 'label' => '采购申请', 'group' => '采购管理', 'code_prefix' => 'QG', 'title_field' => 'code', 'roles' => ['procurement', 'production_manager', 'production', 'engineering'], 'write_roles' => ['procurement'],
            'fields' => [
                $select('requester', '需求方', ['生产', '技术', '业务'], ['required' => true]),
                $relation('material_id', '物料', 'material', ['required' => true]),
                $number('qty', '需求数量', ['required' => true]),
                $select('unit', '单位', $units),
                $relation('project_id', '关联项目', 'project'),
                $select('urgency', '紧急程度', ['普通', '紧急', '特急']),
                $field('reason', '原因'),
                $select('status', '状态', ['待处理', '已转采购', '已驳回']),
            ],
        ],
        [
            'key' => 'inbound', 'label' => '原材料入库单', 'group' => '历史库存（已停用）', 'code_prefix' => 'RK', 'title_field' => 'code', 'roles' => [], 'write_roles' => [], 'archived' => true,
            'fields' => [
                $code('inbound_no', '入库单号'),
                $date('in_date', '入库日期'),
                $creatableRelation('material_id', '物资名称', 'material', ['scope' => 'item', 'required' => true]),
                $field('material_model', '材质', 'text', ['scope' => 'item']),
                $field('spec', '规格尺寸', 'text', ['scope' => 'item']),
                $number('length_mm', '长度mm', ['scope' => 'item', 'min' => 0]),
                $number('width_mm', '宽度mm', ['scope' => 'item', 'min' => 0]),
                $number('qty', '数量', ['scope' => 'item', 'required' => true, 'min' => 0]),
                $select('unit', '计量单位', ['张', '根', 'kg', '吨', '桶', '盒', '件', '套'], ['scope' => 'item']),
                $number('weight', '重量', ['scope' => 'item', 'required' => true, 'min' => 0]),
                $field('bin', '库位', 'text', ['scope' => 'item']),
                $field('inbound_by', '入库人'),
            ],
        ],
        [
            'key' => 'outbound', 'label' => '生产领料出库单', 'group' => '历史库存（已停用）', 'code_prefix' => 'CK', 'title_field' => 'code', 'roles' => [], 'write_roles' => [], 'archived' => true,
            'fields' => [
                $code('outbound_no', '领料单号'),
                $date('apply_date', '申请日期'),
                $relation('project_id', '项目', 'project', ['required' => true]),
                $relation('drawing_id', '图纸编号', 'drawing'),
                $relation('team_id', '班组', 'production_team'),
                $relation('material_id', '物资名称', 'material', ['scope' => 'item', 'required' => true]),
                $field('material_model', '材质', 'text', ['scope' => 'item']),
                $field('spec', '规格尺寸', 'text', ['scope' => 'item']),
                $number('length_mm', '长度mm', ['scope' => 'item', 'min' => 0]),
                $number('width_mm', '宽度mm', ['scope' => 'item', 'min' => 0]),
                $number('requested_qty', '申请数量', ['scope' => 'item', 'min' => 0]),
                $select('unit', '计量单位', ['张', '根', 'kg', '吨', '桶', '盒', '件', '套'], ['scope' => 'item']),
                $number('actual_qty', '实发数量', ['scope' => 'item', 'min' => 0]),
                $number('actual_weight', '实发重量', ['scope' => 'item', 'min' => 0]),
                $field('bin', '库位', 'text', ['scope' => 'item']),
                $field('approver', '审批人'),
                $relation('receiver_member_id', '领料人', 'team_member'),
                $field('warehouse_keeper', '库管'),
            ],
        ],
        [
            'key' => 'stock_ledger', 'label' => '库存台账', 'group' => '历史库存（已停用）', 'code_prefix' => 'KC', 'title_field' => 'code', 'roles' => [], 'write_roles' => [], 'archived' => true,
            'fields' => [
                $field('material_code', '物资编码', 'readonly'),
                $relation('material_id', '物资名称', 'material', ['required' => true]),
                $select('material_model', '材质', ['Q235', 'Q235B', 'Q355', 'Q355B', 'ER50-6', '其他']),
                $select('spec', '规格尺寸', ['6mm×1500×6000', '10#槽钢', '40×40方管', '待补充']),
                $field('length_mm', '长度（mm）'),
                $field('width_mm', '宽度（mm）'),
                $number('opening_qty', '期初数量', ['min' => 0]),
                $number('opening_weight', '期初重量kg', ['min' => 0]),
                $number('in_qty', '本期入库数量', ['min' => 0]),
                $number('in_weight', '本期入库重量kg', ['min' => 0]),
                $number('out_qty', '本期出库数量', ['min' => 0]),
                $number('out_weight', '本期出库重量kg', ['min' => 0]),
                $number('balance_qty', '结存数量'),
                $number('balance_weight', '结存重量kg'),
                $select('bin', '库位', ['A区-01', 'B区-01', 'C区-01', 'F区-01', '待分配']),
                $number('minimum_stock', '最低库存', ['min' => 0]),
                $select('below_warn', '是否低于预警', ['是', '否']),
                $date('updated_date', '最后更新日期'),
            ],
        ],
        [
            'key' => 'stocktake', 'label' => '盘点表', 'group' => '历史库存（已停用）', 'code_prefix' => 'PD', 'title_field' => 'code', 'roles' => [], 'write_roles' => [], 'archived' => true,
            'fields' => [
                $code('stocktake_no', '盘点单号'),
                $date('stocktake_date', '盘点日期'),
                $select('stocktake_type', '盘点类型', ['日常抽盘', '月度盘点', '专项盘点', '年度盘点']),
                $select('stock_item', '物资编码/名称', ['GB-Q235-6MM-001', '钢板', '槽钢', '方管', '待补充']),
                $select('material_spec', '材质规格', ['6mm×1500×6000', '10#槽钢', '40×40方管', '待补充']),
                $number('length_mm', '长度mm', ['min' => 0]),
                $number('width_mm', '宽度mm', ['min' => 0]),
                $number('book_qty', '账面数量'),
                $number('real_qty', '实盘数量'),
                $number('diff_qty', '差异数量'),
                $number('diff_weight', '差异重量kg'),
                $select('diff_reason', '差异原因', ['无', '漏记', '错发', '规格混放', '余料未登记', '现场占用']),
                $select('handle_suggestion', '处理意见', ['无', '补单', '调整库位', '追责', '报损', '复盘整改']),
                $select('checker', '盘点人', ['盘点人', '库管', '财务', '主管', '待签字']),
                $select('reviewer', '复核人', ['复核人', '财务', '主管', '仓储负责人', '待签字']),
                $select('handle_status', '处理状态', ['未处理', '处理中', '已完成', '需复盘']),
                $select('stocktake_target_type', '盘点对象类型', ['原材料', '余料']),
            ],
        ],
        [
            'key' => 'leftover_ledger', 'label' => '余料台账', 'group' => '历史库存（已停用）', 'code_prefix' => 'YL', 'title_field' => 'name', 'roles' => [], 'write_roles' => [], 'archived' => true,
            'fields' => [
                $code('leftover_code', '余料编码'),
                $field('name', '余料名称', 'text', ['required' => true]),
                $relation('source_material_id', '来源原材料', 'material'),
                $select('material_model', '材质', ['Q235', 'Q235B', 'Q355', 'Q355B', 'ER50-6', '其他']),
                $field('spec', '规格尺寸'),
                $number('length_mm', '长度mm', ['min' => 0]),
                $number('width_mm', '宽度mm', ['min' => 0]),
                $number('in_qty', '入库数量', ['min' => 0]),
                $number('out_qty', '出库数量', ['min' => 0]),
                $number('balance_qty', '结存数量'),
                $select('unit', '计量单位', ['张', '根', 'kg', '块', '段']),
                $number('in_weight', '入库重量kg', ['min' => 0]),
                $number('out_weight', '出库重量kg', ['min' => 0]),
                $number('balance_weight', '结存重量kg'),
                $select('status', '可用状态', ['可用', '已用完', '报废']),
                $date('in_date', '入库日期'),
                $field('bin', '库位'),
                $field('remark', '备注'),
                $date('updated_date', '最后更新日期'),
            ],
        ],
        [
            'key' => 'leftover_inbound', 'label' => '余料入库单', 'group' => '历史库存（已停用）', 'code_prefix' => 'YLR', 'title_field' => 'code', 'roles' => [], 'write_roles' => [], 'archived' => true,
            'fields' => [
                $code('inbound_no', '入库单号'),
                $date('in_date', '入库日期'),
                $relation('source_material_id', '来源原材料', 'material'),
                $relation('source_outbound_id', '关联生产领料单号', 'outbound'),
                $field('name', '余料名称', 'text', ['required' => true]),
                $select('material_model', '材质', ['Q235', 'Q235B', 'Q355', 'Q355B', 'ER50-6', '其他']),
                $field('spec', '规格尺寸'),
                $number('length_mm', '长度mm', ['min' => 0]),
                $number('width_mm', '宽度mm', ['min' => 0]),
                $relation('source_project_id', '来源项目', 'project'),
                $number('in_qty', '入库数量', ['min' => 0]),
                $select('unit', '计量单位', ['张', '根', 'kg', '块', '段']),
                $number('in_weight', '入库重量kg', ['min' => 0]),
                $field('bin', '库位'),
                $field('inbound_by', '入库人'),
                $select('status', '可用状态', ['可用', '报废']),
                $field('remark', '备注'),
            ],
        ],
        [
            'key' => 'leftover_outbound', 'label' => '余料出库单', 'group' => '历史库存（已停用）', 'code_prefix' => 'YLC', 'title_field' => 'code', 'roles' => [], 'write_roles' => [], 'archived' => true,
            'fields' => [
                $code('outbound_no', '出库单号'),
                $relation('project_id', '使用项目', 'project'),
                $date('out_date', '出库日期'),
                $relation('leftover_id', '余料名称', 'leftover_ledger', ['required' => true]),
                $field('spec', '规格尺寸'),
                $select('material_model', '材质', ['Q235', 'Q235B', 'Q355', 'Q355B', 'ER50-6', '其他']),
                $number('length_mm', '长度mm', ['min' => 0]),
                $number('width_mm', '宽度mm', ['min' => 0]),
                $number('out_qty', '出库数量', ['min' => 0]),
                $select('unit', '计量单位', ['张', '根', 'kg', '块', '段']),
                $number('out_weight', '出库重量kg', ['min' => 0]),
                $select('purpose', '用途', ['再利用', '报废', '销售']),
                $field('receiver', '领用人'),
                $field('remark', '备注'),
            ],
        ],
        [
            'key' => 'production_stat', 'label' => '生产统计表', 'group' => '历史库存（已停用）', 'code_prefix' => 'PR', 'title_field' => 'code', 'roles' => [], 'write_roles' => [], 'archived' => true,
            'fields' => [
                $code('record_no', '记录编号'),
                $date('production_date', '生产日期'),
                $relation('project_id', '所属项目', 'project', ['required' => true]),
                $select('process', '工序', ['切割', '焊接', '总装', '打磨', '其他'], ['required' => true]),
                $relation('team_id', '生产班组', 'production_team'),
                $field('product_name', '半成品名称'),
                $field('spec', '规格型号'),
                $select('material_model', '材质', ['Q235', 'Q235B', 'Q355', 'Q355B', 'ER50-6', '其他']),
                $number('length_mm', '长度mm', ['min' => 0]),
                $number('width_mm', '宽度mm', ['min' => 0]),
                $number('output_qty', '产出数量', ['min' => 0]),
                $select('unit', '计量单位', ['件', '套', 'kg', '张', '根']),
                $number('unit_weight', '单件重量kg', ['min' => 0]),
                $number('output_weight', '产出重量kg', ['min' => 0]),
                $relation('outbound_id', '关联领料单号', 'outbound'),
                $field('remark', '备注'),
            ],
        ],
        [
            'key' => 'project_loss_analysis', 'label' => '项目料损分析', 'group' => '历史库存（已停用）', 'code_prefix' => 'LOSS', 'title_field' => 'code', 'roles' => [], 'write_roles' => [], 'archived' => true,
            'fields' => [
                $relation('project_id', '项目名称', 'project', ['required' => true]),
                $field('project_manager', '项目负责人'),
                $date('project_start_date', '项目开始日期'),
                $date('project_end_date', '项目结束日期'),
                $select('project_status', '项目状态', ['进行中', '已完工', '暂停', '取消']),
                $field('raw_material_out_weight', '原材出库总重量kg', 'readonly', ['readonly' => true]),
                $field('leftover_input_weight', '余料投入重量kg', 'readonly', ['readonly' => true]),
                $field('laser_output_weight', '激光下料产出重量kg', 'readonly', ['readonly' => true]),
                $field('laser_output_qty', '激光下料产出数量', 'readonly', ['readonly' => true]),
                $field('welding_output_weight', '焊接产出重量kg', 'readonly', ['readonly' => true]),
                $field('welding_output_qty', '焊接产出数量', 'readonly', ['readonly' => true]),
                $field('cutting_loss', '切割料损kg', 'readonly', ['readonly' => true]),
                $field('cutting_loss_rate', '切割料损率', 'readonly', ['readonly' => true]),
                $field('welding_loss', '焊接料损kg', 'readonly', ['readonly' => true]),
                $field('welding_loss_rate', '焊接料损率', 'readonly', ['readonly' => true]),
                $field('total_loss', '总损耗kg', 'readonly', ['readonly' => true]),
                $field('total_loss_rate', '总损耗率', 'readonly', ['readonly' => true]),
                $field('cutting_yield_rate', '切割产成率', 'readonly', ['readonly' => true]),
                $field('welding_yield_rate', '焊接产成率', 'readonly', ['readonly' => true]),
                $number('leftover_recovery_estimate', '余料回收估算kg', ['min' => 0]),
                $field('remark', '备注'),
            ],
        ],
    ],
];
